import { Nunito } from "next/font/google";
import Header from "@/layouts/header";
import Footer from "@/layouts/footer";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";
import "./globals.css";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={nunito.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
